/**
 * 공통 에러 코드 테이블
 * @description 도메인별 식별 가능한 에러 코드를 정의
 */
export const ERROR_CODES = {
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_EMAIL_NOT_FOUND: 'AUTH_EMAIL_NOT_FOUND',
  AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_PHONE_ALREADY_EXISTS: 'AUTH_PHONE_ALREADY_EXISTS',
  AUTH_INVALID_CURRENT_PASSWORD: 'AUTH_INVALID_CURRENT_PASSWORD',

  PASSWORD_INVALID_RESET_CODE: 'PASSWORD_INVALID_RESET_CODE',
  PASSWORD_TOO_MANY_REQUESTS: 'PASSWORD_TOO_MANY_REQUESTS',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
